version: '2'

services:
      server:
            build: ./server
            ports:
                  - 7001:7001
            volumes:
                  - ./server:/src/app
            container_name: sample_server
            command: npm run start_on_docker
            depends_on:
                  - mysql
            environment:
                  - DATABASE_HOST=mysql

      dashboard:
            build: ./dashboard
            ports:
                  - 8000:80
            container_name: sample_dashboard

      mysql:
            build: ./mysql
            ports:
                  - 3306:3306
            container_name: sample_mysql
            volumes:
                  - ~/mysql/data:/var/lib/mysql
                  - ~/mysql/log:/var/log/mysql
            environment:
                  MYSQL_ROOT_PASSWORD: root
                  # MYSQL_DATABASE: cg_apiserver